---

################################
# DEPENDENCIES
################################

- name: Install prerequisite apt packages
  when: ombi_toggles_enable_apt_packages
  ansible.builtin.apt:
    pkg:
      - python3-requests
      - python3-pymysql
      - python3-lxml
    update_cache: true

################################
# DOCKER
################################

- name: Apt install docker if required
  when:
    - ombi_toggles_enable_docker_install
    - ansible_os_family == 'Debian'
  block:
    - name: Gather apt facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Include docker install tasks
      when: '"docker-ce" not in ansible_facts.packages'
      ansible.builtin.include_tasks: sub_tasks/docker.yml

################################
# CLEAN UP
################################

- name: Register container
  community.docker.docker_container_info:
    name: '{{ ombi_basics_name }}'
  register: ombi_existing_container_result

- name: Remove existing container
  when: ombi_existing_container_result.exists
  community.docker.docker_container:
    container_default_behavior: compatibility
    name: '{{ ombi_basics_name }}'
    state: absent
    stop_timeout: 10
  register: ombi_remove_docker_container
  retries: 5
  delay: 10
  until: ombi_remove_docker_container is succeeded

################################
# TIMEZONE
################################

- name: Get IP geolocation data
  community.general.ipinfoio_facts:

- name: Set timezone variable
  ansible.builtin.set_fact:
    timezone: '{{ ansible_facts.timezone }}'

################################
# BACKEND NETWORK
################################

- name: Conduct backend network tasks
  block:
    - name: Register backend network
      community.docker.docker_network_info:
        name: '{{ ombi_network_backend }}'
      register: ombi_network_backend_result

    - name: Network backend builtin fail
      ansible.builtin.fail:
        msg: Backend network does not exist nor is it enabled. Ensure the backend network variables contain valid entries.
      when:
        - not ombi_network_backend_is_enabled
        - not ombi_network_backend_result.exists

    - name: Create backend network
      when:
        - ombi_network_backend_is_enabled
        - not ombi_network_backend_result.exists
      community.docker.docker_network:
        name: '{{ ombi_network_backend }}'
        driver: '{{ ombi_network_backend_driver }}'
        ipam_config:
          - subnet: '{{ ombi_network_backend_subnet }}'

################################
# APPDATA
################################

- name: Create appdata directory
  ansible.builtin.file:
    path: '{{ ombi_paths_location }}'
    state: directory
    owner: '{{ ombi_env_puid }}'
    group: '{{ ombi_env_pgid }}'
    mode: '0755'

################################
# MARIADB
################################

- name: Conduct mariadb tasks
  when:
    - ombi_toggles_enable_mariadb
    - mariadb_is_enabled
  block:
    - name: Include mariadb container tasks
      ansible.builtin.include_tasks: mariadb/container.yml

    - name: Include mariadb database tasks
      ansible.builtin.include_tasks: mariadb/database_json.yml

################################
# TRAEFIK
################################

- name: Conduct traefik tasks
  when: ombi_toggles_enable_traefik
  block:
    - name: Traefik builtin fail
      when: not ombi_traefik_is_enabled
      ansible.builtin.fail:
        msg: Traefik is toggled on, but the domain varible is empty.

    - name: Register traefik network
      community.docker.docker_network_info:
        name: '{{ traefik_network }}'
      register: traefik_network_result

    - name: Traefik builtin fail
      when:
        - not traefik_network_is_enabled
        - not traefik_network_result.exists
      ansible.builtin.fail:
        msg: Traefik network does not exist nor is it enabled. Ensure the Traefik network variables contain valid entries.

    - name: Create traefik network
      when: not traefik_network_result.exists
      community.docker.docker_network:
        name: '{{ traefik_network }}'
        driver: '{{ traefik_network_driver }}'
        ipam_config:
          - subnet: '{{ traefik_network_subnet }}'

################################
# CLOUDFLARE
################################

- name: Perform Cloudflare DNS tasks
  when: ombi_toggles_enable_cloudflare_dns
  block:
    - name: Cloudflare builtin fail
      when: not ombi_cloudflare_is_enabled
      ansible.builtin.fail:
        msg: Cloudflare DNS is toggled on, but the cloudflare API token variable is empty.

    - name: Include cloudflare tasks
      ansible.builtin.include_tasks: sub_tasks/cloudflare.yml

################################
# CONTAINER
################################

- name: Create container
  when: not ombi_toggles_enable_traefik
  community.docker.docker_container:
    name: '{{ ombi_basics_name }}'
    image: '{{ ombi_basics_image_repo }}:{{ ombi_basics_image_tag }}'
    networks: '{{ ombi_networks }}'
    env:
      PUID: '{{ ombi_env_puid }}'
      PGID: '{{ ombi_env_pgid }}'
      TZ: '{{ timezone }}'
    ports:
      - '{{ ombi_ports_host }}:{{ ombi_ports_cont }}'
    volumes: '{{ ombi_bind_mount }}'
    restart_policy: '{{ ombi_basics_restart_policy }}'

- name: Create traefik container
  when: ombi_toggles_enable_traefik
  community.docker.docker_container:
    name: '{{ ombi_basics_name }}'
    image: '{{ ombi_basics_image_repo }}:{{ ombi_basics_image_tag }}'
    networks: '{{ ombi_networks }}'
    env:
      PUID: '{{ ombi_env_puid }}'
      PGID: '{{ ombi_env_pgid }}'
      TZ: '{{ timezone }}'
    labels: '{{ ombi_labels }}'
    ports:
      - '{{ ombi_ports_host }}:{{ ombi_ports_cont }}'
    volumes: '{{ ombi_bind_mount }}'
    restart_policy: '{{ ombi_basics_restart_policy }}'
