---

################################
# APPDATA
################################

- name: Create mariadb appdata directory
  ansible.builtin.file:
    path: '{{ mariadb_paths_location }}'
    state: directory
    owner: '{{ mariadb_env_puid }}'
    group: '{{ mariadb_env_pgid }}'
    mode: '0755'

################################
# KEYS
################################

- name: Create mariadb keys directory
  ansible.builtin.file:
    path: '{{ mariadb_paths_keys_location }}'
    state: directory
    owner: '{{ mariadb_env_puid }}'
    group: '{{ mariadb_env_pgid }}'
    mode: '0755'

- name: Check if mariadb_root.txt exists
  ansible.builtin.stat:
    path: '{{ mariadb_paths_keys_location }}/{{ mariadb_auth_root_password_file }}'
  register: mariadb_root_txt

- name: Insert mariadb root password into file
  when: not mariadb_root_txt.stat.exists
  ansible.builtin.lineinfile:
    path: '{{ mariadb_paths_keys_location }}/{{ mariadb_auth_root_password_file }}'
    line: '{{ mariadb_auth_root_password }}'
    owner: '{{ mariadb_env_puid }}'
    group: '{{ mariadb_env_pgid }}'
    mode: '0644'
    create: true

- name: Check if mariadb_ombi.txt exists
  ansible.builtin.stat:
    path: '{{ mariadb_paths_keys_location }}/{{ mariadb_ombi_db_password_file }}'
  register: ombi_mariadb_db_key_txt

- name: Insert mariadb db password into file
  when: not ombi_mariadb_db_key_txt.stat.exists
  ansible.builtin.lineinfile:
    path: '{{ mariadb_paths_keys_location }}/{{ mariadb_ombi_db_password_file }}'
    line: '{{ mariadb_ombi_db_password }}'
    owner: '{{ mariadb_env_puid }}'
    group: '{{ mariadb_env_pgid }}'
    mode: '0644'
    create: true

################################
# NETWORK
################################

- name: Register mariadb network
  community.docker.docker_network_info:
    name: '{{ mariadb_network }}'
  register: mariadb_network_result

- name: Mariadb network builtin fail
  ansible.builtin.fail:
    msg: Mariadb network does not exist nor is it enabled. Ensure the Mariadb network variables contain valid entries.
  when:
    - not mariadb_network_is_enabled
    - not mariadb_network_result.exists

- name: Create mariadb network
  when: not mariadb_network_result.exists
  community.docker.docker_network:
    name: '{{ mariadb_network }}'
    driver: '{{ mariadb_network_driver }}'
    ipam_config:
      - subnet: '{{ mariadb_network_subnet }}'

################################
# CONTAINER
################################

- name: Register mariadb container
  community.docker.docker_container_info:
    name: '{{ mariadb_basics_name }}'
  register: mariadb_container_result

- name: Create mariadb container
  when: not mariadb_container_result.exists
  community.docker.docker_container:
    name: '{{ mariadb_basics_name }}'
    image: '{{ mariadb_basics_image_repo }}:{{ mariadb_basics_image_tag }}'
    networks:
      - name: '{{ mariadb_network }}'
    env:
      PUID: '{{ mariadb_env_puid }}'
      PGID: '{{ mariadb_env_pgid }}'
      TZ: '{{ timezone }}'
      MARIADB_ROOT_PASSWORD_FILE: '/keys/{{ mariadb_auth_root_password_file }}'
      MARIADB_DATABASE: '{{ mariadb_ombi_database }}'
      MARIADB_USER: '{{ mariadb_ombi_db_user }}'
      MARIADB_PASSWORD_FILE: '/keys/{{ mariadb_ombi_db_password_file }}'
    ports:
      - '{{ mariadb_ports_host }}:{{ mariadb_ports_cont }}'
    volumes: '{{ mariadb_binds }}'
    restart_policy: '{{ mariadb_basics_restart_policy }}'

- name: Make sure the mariadb container is started
  community.docker.docker_container:
    name: '{{ mariadb_basics_name }}'
    state: started
  register: start_mariadb_docker
  retries: 5
  delay: 10
  until: start_mariadb_docker is succeeded