---

- name: Remove existing database.json
  ansible.builtin.file:
    path: '{{ lookup("vars", role_prefix + "_paths_location") }}/database.json'
    state: absent

- name: Import ombi database.json
  ansible.builtin.template:
    src: '{{ role_path }}/templates/database.json.j2'
    dest: '{{ lookup("vars", role_prefix + "_paths_location") }}/database.json'
    force: true
    owner: '{{ lookup("vars", role_prefix + "_env_puid") }}'
    group: '{{ lookup("vars", role_prefix + "_env_pgid") }}'
    mode: '0664'

- name: Remove sqlite database files
  when: (lookup("vars", role_prefix + "_toggles_clean_files"))
  ansible.builtin.file:
    path: '{{ lookup("vars", role_prefix + "_paths_location") }}/{{ item }}'
    state: absent
  loop:
    - Ombi.db
    - OmbiExternal.db
    - OmbiSettings.db