---

################################
# DOMAIN
################################

ombi_traefik_subdomain: '{{ ombi_basics_name }}'
ombi_traefik_domain: ''
ombi_traefik_port: '{{ ombi_ports_cont }}'

################################
# NETWORK
################################

traefik_network: 'traefik_proxy'
traefik_network_driver: 'bridge'  ## only required if network doesn't exist
traefik_network_subnet: ''  ## only required if network doesn't exist

################################
# TLS
################################

traefik_tls_certresolver: 'dns-cloudflare'
traefik_tls_options: 'tls-opts@file'

################################
# ROUTER (HTTP)
################################

ombi_traefik_http_middlewares: 'globalHeaders@file,redirect-to-https@docker,autodetect@docker,gzip@docker,robotHeaders@file'
ombi_traefik_http_rule: 'Host(`{{ ombi_traefik_subdomain }}.{{ ombi_traefik_domain }}`)'
ombi_traefik_http_priority: '20'

################################
# ROUTER (HTTPS)
################################

ombi_traefik_https_middlewares: 'globalHeaders@file,secureHeaders@file,autodetect@docker,gzip@docker,robotHeaders@file,hsts@file'
ombi_traefik_https_rule: 'Host(`{{ ombi_traefik_subdomain }}.{{ ombi_traefik_domain }}`)'
ombi_traefik_https_priority: '20'