---

- name: Remove existing CNAME DNS record
  community.general.cloudflare_dns:
    api_token: '{{ ombi_cloudflare_api_token }}'
    zone: '{{ ombi_cloudflare_zone }}'
    state: absent
    type: CNAME
    record: '{{ ombi_cloudflare_record }}'

- name: Remove existing A DNS record
  community.general.cloudflare_dns:
    api_token: '{{ ombi_cloudflare_api_token }}'
    zone: '{{ ombi_cloudflare_zone }}'
    state: absent
    type: A
    record: '{{ ombi_cloudflare_record }}'

- name: Get public ip for DNS tasks
  block:
    - name: Get public IP
      community.general.ipify_facts:
        timeout: 20
      delegate_to: localhost
      register: public_ip

    - name: Public IP output
      ansible.builtin.debug:
        msg: '{{ ipify_public_ip }}'

- name: Add ombi DNS record
  community.general.cloudflare_dns:
    api_token: '{{ ombi_cloudflare_api_token }}'
    zone: '{{ ombi_cloudflare_zone }}'
    state: present
    solo: true
    proxied: '{{ ombi_cloudflare_proxy }}'
    type: '{{ ombi_cloudflare_record_type }}'
    value: '{{ ipify_public_ip }}'
    record: '{{ ombi_cloudflare_record }}'
  register: ombi_cloudflare_record_creation_status

- name: Tasks on success
  when: ombi_cloudflare_record_creation_status is succeeded
  block:
    - name: Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        ombi_cloudflare_record_print: '{{ (ombi_cloudflare_record == ombi_cloudflare_zone) | ternary(ombi_cloudflare_zone, ombi_cloudflare_record + "." + ombi_cloudflare_zone) }}'

    - name: Display DNS record creation status
      ansible.builtin.debug:
        msg: 'DNS A Record for "{{ ombi_cloudflare_record_print }}" set to "{{ ipify_public_ip }}" was added. Proxy: {{ ombi_cloudflare_proxy }}'
